// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecursosHumanos.Models;

#nullable disable

namespace RecursosHumanos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecursosHumanos.Models.Base", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Base1")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Base");

                    b.Property<DateTime>("FechaCreación")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Base__3214EC074BC0B040");

                    b.ToTable("Base", "Reclutamiento");
                });

            modelBuilder.Entity("RecursosHumanos.Models.CatalogoCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diploma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<int?>("IdDepartamentoNavigationId")
                        .HasColumnType("int");

                    b.Property<int?>("IdNivel")
                        .HasColumnType("int");

                    b.Property<int?>("IdNivelNavigationId")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoCurso")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoCursoNavigationId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDepartamentoNavigationId");

                    b.HasIndex("IdNivelNavigationId");

                    b.HasIndex("IdTipoCursoNavigationId");

                    b.ToTable("CatalogoCursos");
                });

            modelBuilder.Entity("RecursosHumanos.Models.CatalogoNivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatalogoNivels");
                });

            modelBuilder.Entity("RecursosHumanos.Models.DatosReclutamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasMaxLength(2555)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2555)");

                    b.Property<DateTime>("FechaContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("FechaCreación")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdBase")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstatus")
                        .HasColumnType("int");

                    b.Property<int?>("IdFuente")
                        .HasColumnType("int");

                    b.Property<int?>("IdPosicion")
                        .HasColumnType("int");

                    b.Property<int?>("IdReclutador")
                        .HasColumnType("int");

                    b.Property<int?>("IdSexo")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Datos_Re__3214EC07A4DE686C");

                    b.HasIndex("IdBase");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdEstatus");

                    b.HasIndex("IdFuente");

                    b.HasIndex("IdPosicion");

                    b.HasIndex("IdReclutador");

                    b.HasIndex("IdSexo");

                    b.ToTable("Datos_Reclutamiento", "Reclutamiento");
                });

            modelBuilder.Entity("RecursosHumanos.Models.DatosReclutamientoReflejo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Base")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Estatus")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Fuente")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Posicion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Reclutador")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Datos_Re__3214EC07155A07DC");

                    b.ToTable("Datos_Reclutamiento_Reflejo", "Reclutamiento");
                });

            modelBuilder.Entity("RecursosHumanos.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("RecursosHumanos.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Empresa1")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Empresa");

                    b.Property<DateTime>("FechaCreación")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Empresa__3214EC0716581833");

                    b.ToTable("Empresa", "Reclutamiento");
                });

            modelBuilder.Entity("RecursosHumanos.Models.Estatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estatus1")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Estatus");

                    b.Property<DateTime>("FechaCreación")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Estatus__3214EC072F975721");

                    b.ToTable("Estatus", "Reclutamiento");
                });

            modelBuilder.Entity("RecursosHumanos.Models.Fuente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreación")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Fuente1")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Fuente");

                    b.HasKey("Id")
                        .HasName("PK__Fuente__3214EC0784036524");

                    b.ToTable("Fuente", "Reclutamiento");
                });

            modelBuilder.Entity("RecursosHumanos.Models.Posicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreación")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Posicion1")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Posicion");

                    b.HasKey("Id")
                        .HasName("PK__Posicion__3214EC07E21C48C7");

                    b.ToTable("Posicion", "Reclutamiento");
                });

            modelBuilder.Entity("RecursosHumanos.Models.Reclutador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreación")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Reclutad__3214EC0739300128");

                    b.ToTable("Reclutador", "Reclutamiento");
                });

            modelBuilder.Entity("RecursosHumanos.Models.Sexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreación")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Sexo1")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Sexo");

                    b.HasKey("Id")
                        .HasName("PK__Sexo__3214EC072F6FFB1B");

                    b.ToTable("Sexo", "Reclutamiento");
                });

            modelBuilder.Entity("RecursosHumanos.Models.TipoCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoCursos");
                });

            modelBuilder.Entity("RecursosHumanos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("correo");

                    b.Property<bool>("EsAdministrador")
                        .HasColumnType("bit")
                        .HasColumnName("es_administrador");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Usuario1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Usuario");

                    b.HasKey("Id")
                        .HasName("PK__usuarios__3214EC0764D14EAE");

                    b.ToTable("usuarios", "Usuario");
                });

            modelBuilder.Entity("RecursosHumanos.Models.UsuarioEspejo", b =>
                {
                    b.Property<string>("Contraseña")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("correo");

                    b.Property<string>("EsAdministrador")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("es_administrador");

                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ID");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Usuario")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.ToTable("UsuarioEspejo", "Usuario");
                });

            modelBuilder.Entity("RecursosHumanos.Models.CatalogoCurso", b =>
                {
                    b.HasOne("RecursosHumanos.Models.Departamento", "IdDepartamentoNavigation")
                        .WithMany("CatalogoCursos")
                        .HasForeignKey("IdDepartamentoNavigationId");

                    b.HasOne("RecursosHumanos.Models.CatalogoNivel", "IdNivelNavigation")
                        .WithMany("CatalogoCursos")
                        .HasForeignKey("IdNivelNavigationId");

                    b.HasOne("RecursosHumanos.Models.TipoCurso", "IdTipoCursoNavigation")
                        .WithMany("CatalogoCursos")
                        .HasForeignKey("IdTipoCursoNavigationId");

                    b.Navigation("IdDepartamentoNavigation");

                    b.Navigation("IdNivelNavigation");

                    b.Navigation("IdTipoCursoNavigation");
                });

            modelBuilder.Entity("RecursosHumanos.Models.DatosReclutamiento", b =>
                {
                    b.HasOne("RecursosHumanos.Models.Base", "IdBaseNavigation")
                        .WithMany("DatosReclutamientos")
                        .HasForeignKey("IdBase")
                        .HasConstraintName("FK_Base_Nombre");

                    b.HasOne("RecursosHumanos.Models.Empresa", "IdEmpresaNavigation")
                        .WithMany("DatosReclutamientos")
                        .HasForeignKey("IdEmpresa")
                        .HasConstraintName("FK_Empresa_Nombre");

                    b.HasOne("RecursosHumanos.Models.Estatus", "IdEstatusNavigation")
                        .WithMany("DatosReclutamientos")
                        .HasForeignKey("IdEstatus")
                        .HasConstraintName("FK_Estatus_Nombre");

                    b.HasOne("RecursosHumanos.Models.Fuente", "IdFuenteNavigation")
                        .WithMany("DatosReclutamientos")
                        .HasForeignKey("IdFuente")
                        .HasConstraintName("FK_Fuente_Nombre");

                    b.HasOne("RecursosHumanos.Models.Posicion", "IdPosicionNavigation")
                        .WithMany("DatosReclutamientos")
                        .HasForeignKey("IdPosicion")
                        .HasConstraintName("FK_Posicion_Nombre");

                    b.HasOne("RecursosHumanos.Models.Reclutador", "IdReclutadorNavigation")
                        .WithMany("DatosReclutamientos")
                        .HasForeignKey("IdReclutador")
                        .HasConstraintName("FK_Reclutador_Nombre");

                    b.HasOne("RecursosHumanos.Models.Sexo", "IdSexoNavigation")
                        .WithMany("DatosReclutamientos")
                        .HasForeignKey("IdSexo")
                        .HasConstraintName("FK_Sexo_Nombre");

                    b.Navigation("IdBaseNavigation");

                    b.Navigation("IdEmpresaNavigation");

                    b.Navigation("IdEstatusNavigation");

                    b.Navigation("IdFuenteNavigation");

                    b.Navigation("IdPosicionNavigation");

                    b.Navigation("IdReclutadorNavigation");

                    b.Navigation("IdSexoNavigation");
                });

            modelBuilder.Entity("RecursosHumanos.Models.Base", b =>
                {
                    b.Navigation("DatosReclutamientos");
                });

            modelBuilder.Entity("RecursosHumanos.Models.CatalogoNivel", b =>
                {
                    b.Navigation("CatalogoCursos");
                });

            modelBuilder.Entity("RecursosHumanos.Models.Departamento", b =>
                {
                    b.Navigation("CatalogoCursos");
                });

            modelBuilder.Entity("RecursosHumanos.Models.Empresa", b =>
                {
                    b.Navigation("DatosReclutamientos");
                });

            modelBuilder.Entity("RecursosHumanos.Models.Estatus", b =>
                {
                    b.Navigation("DatosReclutamientos");
                });

            modelBuilder.Entity("RecursosHumanos.Models.Fuente", b =>
                {
                    b.Navigation("DatosReclutamientos");
                });

            modelBuilder.Entity("RecursosHumanos.Models.Posicion", b =>
                {
                    b.Navigation("DatosReclutamientos");
                });

            modelBuilder.Entity("RecursosHumanos.Models.Reclutador", b =>
                {
                    b.Navigation("DatosReclutamientos");
                });

            modelBuilder.Entity("RecursosHumanos.Models.Sexo", b =>
                {
                    b.Navigation("DatosReclutamientos");
                });

            modelBuilder.Entity("RecursosHumanos.Models.TipoCurso", b =>
                {
                    b.Navigation("CatalogoCursos");
                });
#pragma warning restore 612, 618
        }
    }
}
